name:                rapanui
version:             0.1.0
github:              "githubuser/demo3"
license:             BSD3
author:              "Rolf C Stadheim"
maintainer:          "rolf.c.stadheim@gmail.com"
copyright:           "2023 Rolf C Stadheim"

# extra-source-files:
# - README.md
# - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/demo3#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring
- bytestring-conversion
- cmdargs 
- containers
- exceptions
- hasql
- hspec
- mtl
- optparse-applicative
- req 
- split
- text
- time
- transformers
- tz
- utf8-string
- vector

library:
  source-dirs: src

default-extensions:
  StrictData
  OverloadedStrings
  #ImportQualifiedPost
  #LambdaCase
  #DerivingStrategies
  #DuplicateRecordFields
  #OverloadedRecordDot
  #BlockArguments
  #MultiWayIf

executables:
  rapanui-0.1.0:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wcompat
    - -Widentities
    - -Wpartial-fields
    - -Wredundant-constraints

    dependencies:
    - rapanui 

tests:
  rapanui-test:
    main:                Spec.hs
    source-dirs:         t
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rapanui
